// Code generated by branchkit-gen from plugin.json `action_types`. DO NOT EDIT.
// Regenerate from the plugin directory: branchkit-gen --plugin .

/** Params shape for action "helloworld.greet (Greet)". */
export interface GreetParams {
  name?: string;
}

