// AUTO-GENERATED by emit-sdk — do not edit.
// Source: plugin.json `action_types`. Run: just gen-plugins

/** Params shape for action "hello.greet (Greet)". */
export interface GreetParams {
  name?: string;
}

