// Code generated by branchkit-gen from plugin.json `action_types`. DO NOT EDIT.
// Regenerate from the plugin directory: branchkit-gen --plugin .

import type { Plugin } from "@branchkitdev/plugin-sdk-ts";

/** Params shape for action "helloworld.greet (Greet)". */
export interface GreetParams {
  name?: string;
}

/** Register a typed handler for action "helloworld.greet (Greet)". */
export function handleGreet(
  plugin: Plugin,
  fn: Parameters<typeof plugin.handleAction<GreetParams>>[1],
): void {
  plugin.handleAction<GreetParams>("helloworld.greet", fn);
}

